RESCACHED.CONF(5)
=================
:doctype: manpage
:man source: rescached.cfg
:man version: 2017.02.23
:man manual: rescached.cfg


== NAME

rescached.cfg - Configuration for rescached service


== SYNOPSIS

/etc/rescached/rescached.cfg


== DESCRIPTION

These file configure the behaviour of *rescached*(1) service.
In those file you can see some comment for any option and some possible value.
This section will explain more about each option and how they effect
+rescached+.

The configuration is using INI format where each options is grouped by header
in square bracket:

* +[rescached]+
* +[log]+


== OPTIONS

=== +[rescached]+

This group of options contain the main configuration.

[[file.data]]
==== +file.data+

Value::		A path to a cache file.
Format:: 	/any/path/to/file
Default::	rescached.vos (in current directory)
Description:: 	This file contain all DNS answers that rescached collected
while running.
When +rescached+ stopped it will saved all DNS answer in this file, so when
+rescached+ is started again it will load all data in this file to memory
again.
If not set, then +rescached+ will load/save the cache to the file named
+rescached.vos+ in current directory where user running +rescached+.

[[file.pid]]
==== +file.pid+

Value:: 	A path to process id file.
Format:: 	/any/path/to/file
Default:: 	rescached.pid (in current directory)
Description:: 	When +rescached+ started, it will create this file as a
mediator to any system service.
Content of this file is the process ID (PID) of +rescached+ in system.
If not set then the default name will be used, and it will be saved in current
directory where user running +rescached+.

[[file.log]]
==== +file.log+

[horizontal]
Value:: 	A name of rescached log file.
Format:: 	/any/path/to/file
Default:: 	rescached.log (in current directory)
Description:: 	This file contain log of program when running.
Verbosity of log output is depend on value of +debug+ option.

[[server.parent]]
==== +server.parent+

Value:: 	List of parent DNS servers, separated by commas.
Format:: 	IP-ADDRESS:PORT, IP-ADDRESS:PORT, ...
Default::
* Address: 8.8.8.8, 8.8.4.4
* Port: 53
Description:: 	When +rescached+ receive a query from client and when it does
not have a cached address of query, it will pass the query to those parent
server.
+rescached+ use a Google DNS public server as a default parent address if not set.
The reason for this is that Google DNS public server use a simple and small
size of response/answer.
Please, do not use OpenDNS server.
OpenDNS will reply with its own address, instead of replying with no answer,
if certain host-name not found (i.e. typo in host-name), this will make
+rescached+ caching a false data.
To check if your parent server reply the unknown host-name with no answer, use
*resolver*(1) tool.

[[server.parent.connection]]
==== +server.parent.connection+

Value:: Request to parent server using specific protocol.
Format:: String ("udp" or "tcp", without quotes)
Default:: udp
Description:: Type of protocol that will be used to send request to
+server.parent+.
When +rescached+ receive query from client it will forward the query to the
+server.parent+ using default protocol (UDP).
In case UDP is blocked, you can set this variable to "tcp".

[[server.listen]]
==== +server.listen+

Value:: 	Local IP address that +rescached+ will listening for client
request.
Format:: 	<IP-ADDRESS>:<PORT>
Default:: 	127.0.0.1:53
Description:: 	Address in local network where +rescached+ will listening for
query from client.
If you want rescached to serve a query from another host in your local
network, change this value to +0.0.0.0:53+.

[[server.timeout]]
==== +server.timeout+

Value:: 	Timeout value, in second, before cleaning queue.
Format:: 	Any integer number between 300 to 2147483647.
Default:: 	300
Description:: 	This option set the server timeout value.
If time out is reached, all the old queries (that is older than
+server.timeout+) in queue that does not receive a reply from parent server
will be removed.

[[cache.max]]
==== +cache.max+

Value:: 	Maximum number of host-name and address that will keep in
memory.
Format:: 	Any number between 1 and 2147483647.
Default:: 	100000
Description:: 	When +rescached+ running it will keep all queries and answers
in memory as much as +cache.max+. The bigger the +cache.max+ value, then the
more rescached will use memory.

[[cache.threshold]]
==== +cache.threshold+

Value:: 	Minimum value for cache status.
Format:: 	Any integer number between 1 and 2147483647.
Default:: 	1
Description:: 	When +rescached+ cache all the queries and answers, until long
enough it will reached its own maximum value (+cache.max+), when it happen
+rescached+ will remove all cache that has number-of-queried value is less
than +cache.threshold+.

[[cache.minttl]]
==== +cache.minttl+

Value:: Set DNS record TTL to this value if their original TTL is less than
this.
Format:: in seconds, any number from 1 to 2147483647.
Default:: 60 (1 minute).
Description:: Nowaday DNS record last only 60 second.
Saving it permanently will cause wrong connection from client (probably 404 or
host not found), while saving it temporarily will cause many cache misses.
Our solution to this problem is by allowing user to replace TTL value in DNS
record with this value only if below it.

[[debug]]
==== +debug+

Value::
0::: log nothing.
1::: log startup, request, response, and exit status.
2::: log startup, request, response, caches, and exit status.
Format:: 	Number (0, 1, or 2).
Default:: 	0
Description:: 	This option only used by developer for debugging program or if
user want to monitor what kind of traffic goes out, set this option to 1.


=== +[log]+

This group of options affect on log output.

[[show_timestamp]]
==== +show_timestamp+

Value::
0::: do not show timestamp in log output.
1::: show timestamp in log output.
Format::	Number (0 or 1)
Default::	0
Description::	If set to non-zero, each line in log output will added with
timestamp format "[YYYY.MM.DD HH:mm:SS] ".

[[show_appstamp]]
==== +show_appstamp+

Value::
0::: do not show application stamp.
1::: show application stamp.
Format::	Number (0 or 1)
Default::	0
Description::	If set to non-zero,  each line in log output will be added
with application ## stamp "[rescached] ", after timestamp and before actual
log string.


== EXAMPLE

Simple rescached configuration using dnscrypt-proxy that listen on port 54 as
parent resolver, with maximum cache are 1000 hostnames, and threshold is 5.

..............................................................................
[rescached]
server.parent=127.0.0.1:54
cache.max=1000
threshold=5
..............................................................................

Save the above script into +rescached.cfg+ and run it,

	$ sudo rescached rescached.cfg


== AUTHOR

+rescached+ is developed by M. Shulhan (ms@kilabit.info).


== LICENSE

Copyright 2009-2017, M. Shulhan (ms@kilabit.info).
All rights reserved.

Use of this source code is governed by a BSD-style license that can be found
in the LICENSE file.



== SEE ALSO

*rescached*(1)
